apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps
resources:
  - jellystack-sealedsecret.yaml
  - ../../base/jellystack
patches:
  - path: jellystack-values.yaml
    target:
      kind: HelmRelease
