apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomizations
resources:
  - bitnami.yaml
  - ingress-nginx.yaml
  - istio.yaml
  - jetstack.yaml
  - kubernetes-csi.yaml
  - longhorn.yaml
  - authentik.yaml