---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: talos-control-plane-pool
  namespace: metallb-system
spec:
  addresses:
    - $(IP_ADDRESS_RANGE)
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: talos-l2advertisement
  namespace: metallb-system