apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: default
spec:
  suspend: false
  force: false
  wait: true
  interval: 30s
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-sync
    namespace: flux-system
  path: ./infrastructure/cert-manager/controller
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certs
  namespace: default
spec:
  dependsOn:
    - name: cert-manager
  suspend: false
  force: false
  wait: true
  interval: 30s
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-sync
    namespace: flux-system
  path: ./infrastructure/cert-manager/certs
  prune: true